on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
permissions: write-all

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create package
        run: |
           npm install
           npm install -g pkg
           pkg package.json
           mv festivalmanager.exe festivalmanager-${{ github.ref_name }}.exe
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: New Release with improvements
          draft: false
          prerelease: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: festivalmanager-${{ github.ref_name }}.exe
          asset_name: festivalmanager-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the new release."

