# Tag a commit with a version number and 
# this action will build a .exe for it
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
permissions: write-all

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Build .exe file and name it
      - name: Create package
        run: |
           # install packages
           npm install
           npm install -g pkg
           # enable vuejs production
           cp dist/public/js/vue-prod-3.2.45.js dist/public/js/vue-3.2.45.js
           # s"--no-bytecode --public-packages "*" --public" workaround for https://github.com/vercel/pkg/issues/1663
           pkg package.json --no-bytecode --public-packages "*" --public
           mv festivalmanager-win-x64.exe festivalmanager-${{ github.ref_name }}.exe
           mv festivalmanager-linux-arm64 festivalmanager-${{ github.ref_name }}
        shell: bash
      # Create a github release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: New Release with improvements
          draft: false
          prerelease: true
      # Upload .exe file to github release
      - name: Upload windows x64 binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: festivalmanager-${{ github.ref_name }}.exe
          asset_name: festivalmanager-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "${{ github.event.head_commit.message }}"
      # Upload linux file to github release
      - name: Upload arm linux binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: festivalmanager-${{ github.ref_name }}
          asset_name: festivalmanager-${{ github.ref_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "${{ github.event.head_commit.message }}"

